[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

lib_deps =
    adafruit/Adafruit INA219 @ ^1.2.3
    adafruit/Adafruit MCP4725 @ ^2.0.2
    adafruit/Adafruit BusIO @ ^1.16.1

lib_compat_mode = off

monitor_speed = 115200

; -I aponta o include/ do projeto para todas as unidades de compilação,
; incluindo as libs em lib/app, lib/control e lib/hal.
build_flags =
    -std=gnu++17
    -I include
